// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
// #[primary_key(company_id)]
// #[table_name = "Company"]
pub struct Company {
    pub company_id: String,
    pub location: Option<String>,
    pub name: Option<String>,
}

#[derive(Queryable, Debug)]
// #[primary_key(emp_code)]
// #[table_name = "Employee"]
pub struct Employee {
    pub emp_code: String,
    pub comp_id: String,
}

#[derive(Queryable, Debug)]
// #[primary_key(nslf)]
// #[table_name = "Receipt"]
pub struct Receipt {
    pub nslf: String,
    pub nivf: String,
    pub value_before_tvsh: Option<f64>,
    pub tvsh: Option<f64>,
    pub value: f64,
    pub location: Option<String>,
    pub release_date: NaiveDateTime,
    pub receipt_type: Option<String>,
    pub sw_code: Option<String>,
    pub payment_deadline: Option<NaiveDateTime>,
    pub status: Option<String>,
    pub business_id: String,
    pub operator_id: String,
    pub user_id: i64,
}

#[derive(Queryable, Debug)]
// #[primary_key(user_id)]
// #[table_name = "User"]
pub struct User {
    pub user_id: i64,
    pub registered_on: Option<NaiveDateTime>,
    pub last_upload: Option<NaiveDateTime>,
    pub is_admin: Option<bool>,
}

